apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../base/charts

resources:
- app-of-apps/trancking-micro-services
# - app-tracking/trancking-micro-services
# - projects/web-trackeo-pricing
