apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.appTwo.appName }}-{{ .Values.environment }}
  namespace: argocd
  finalizers: {{ .Values.appOne.finalizers | toYaml | nindent 4 }}
spec:
  destination: 
    server: {{ .Values.appOne.destination.server }}
  project: project-{{ .Values.appTwo.projectName }}-{{.Values.environment}}
  source:
    path: {{ .Values.appTwo.source.path }}
    repoURL: {{ .Values.appOne.source.repoURL }}
    targetRevision: {{ .Values.appOne.source.targetRevision }}
  syncPolicy:
    automated: 
      prune: true
      allowEmpty: true
      selfHeal: true
