apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.registrySecret.name }}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  enableOCI: 'true'
  type: {{ .Values.registrySecret.stringData.type }}
  url: {{ .Values.registrySecret.stringData.url }}
  username: {{ .Values.registrySecret.stringData.username }}
  password: {{ .Values.registrySecret.stringData.password }}