apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.repoSecret.name }}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: {{ .Values.repoSecret.stringData.type }}
  url: {{ .Values.repoSecret.stringData.url }}
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
    NhAAAAAwEAAQAAAYEAx32OMZ49klI20sPTq+zHSVJp6xIZV8Zgoto4A9/MAnvcvhXOJa4D
    EH/USPPEGPFBIUotbWUzO1G6cZq0nR7HxQQfx85MxrpSgofmB/mcNlEcd/LXU+b0/QOQeq
    J1LrdcXlq1X8LOushtVItpnJ6bXyb5TpBs6xGWICO64msWhV2ulvyAiIzE99sYsx9dTnSr
    nN8QxnBCwL1Jc9JZXd6DXV60Hyr/wTK1PLALS/O1Wh2tPRPCqSUb5KBYbPMMNmm2rQpBBy
    8gzv2JX+sz+9KDopUBIOMVms6UdMDu8UY29s8niEYGHh1sc6QHxAJ+yjma6bNA9RE8Aj8D
    /vhDKAR6+uJQIudV7zO1C1LY3HpGaBA94UX2r8R9dyJoQ6l29gjJi8KBchouAap4YXqjo6
    2vUIGekqnN1gIi2ks52HKvLJR01eu5Uk4KnIaIKOwFcWXvdediCDeErieDYC9HG3L0FmhH
    upF1xmrnkj9jVgLjhCX5xOihvHyUG7AM/G87t79DAAAFmE/tuUNP7blDAAAAB3NzaC1yc2
    EAAAGBAMd9jjGePZJSNtLD06vsx0lSaesSGVfGYKLaOAPfzAJ73L4VziWuAxB/1EjzxBjx
    QSFKLW1lMztRunGatJ0ex8UEH8fOTMa6UoKH5gf5nDZRHHfy11Pm9P0DkHqidS63XF5atV
    /CzrrIbVSLaZyem18m+U6QbOsRliAjuuJrFoVdrpb8gIiMxPfbGLMfXU50q5zfEMZwQsC9
    SXPSWV3eg11etB8q/8EytTywC0vztVodrT0TwqklG+SgWGzzDDZptq0KQQcvIM79iV/rM/
    vSg6KVASDjFZrOlHTA7vFGNvbPJ4hGBh4dbHOkB8QCfso5mumzQPURPAI/A/74QygEevri
    UCLnVe8ztQtS2Nx6RmgQPeFF9q/EfXciaEOpdvYIyYvCgXIaLgGqeGF6o6Otr1CBnpKpzd
    YCItpLOdhyryyUdNXruVJOCpyGiCjsBXFl73XnYgg3hK4ng2AvRxty9BZoR7qRdcZq55I/
    Y1YC44Ql+cToobx8lBuwDPxvO7e/QwAAAAMBAAEAAAGBAIyHhx6vAWLNJa+tobQwNWcSdm
    jRNCcgKT0vilw4UEfDp4oEZFco0SHTWuEVT6Ped+oSjhPNQZzdAwE6YVd5snK4aAbh7jXk
    VXF8eHBPx1qAIxTgbg292gFOfH3XacNCCgCx16kg2266+EGhgAGDvaH3G5LbrM6fceksIl
    +T3qaOiwnz0DvhJnQP1MOCKcG18JqujOutc2jBLzg3CxtUP6gLqcl3Cfm4VfHtddfIU42q
    8DnhbLSo3pBc4E3HnWfLaVTwLSkkiWcQDc1R628Ie7Ogmp4N0mBTkUab1gZivgxKtPv54F
    U+bIWzB44AVcHL/IsUR2yNilcHg26/y4hLQUZes5GCToh7X+3qQtvI57/1QHpO2cN8fdv7
    XC23sbb8dDhFq0JPUFaKnd5dqH9znO7SM7fKREx/9oudfR1ErT3+rb6X7jUOmlfDo6g7fe
    dPtEKUPZCGKWg2VkB2+SIMpgTLFGboAVhWvoNeWUhvyK8SYmP5pQV2X10v2gXhhjQuEQAA
    AMEAsoBiHWCdErPVq6yqMUlONQpLpUdmwRYksh67o30naIxOIbqFQexQ0PQaCcjM3AzOX3
    yl5t7ORL6OoUEp1H89BsL+znboBxRbjAGFer89CmjXYQXZktNk47HZI3QSe5IDQ0zHsJfo
    iFuEhCGkFFReU5nFeAB7LnsBXONJ6DXUHnT6UUKcROCr4Zzxqf5CJuQTA533p6yx+KZjOZ
    WVql1qtm14DXna6+04G3Pv9YWZUSRVVcrIkYnTM/IA6z1G+rMxAAAAwQDjl0OfoHmyK0N/
    /pEz0IQtXAzh2W0S8gRDTgT/HtBPwe5Pg7as0oSouLOEPx262Ty3yO909nJDyRCsOkEtZ2
    /S2VBey53OLFEAmxzegpce2lHKLTxbyG5cr03GpnmCDmDnm4bliuqGeKEKg5L/XAW1PspU
    JY3a++gWP4RIOdpr4HdqkoEp/PhYNe/bVVnhbVwP5tXzpupqYU8TrtGG69m9gH09+5EGKK
    HBNcoaDQJx/8lXQd5vfVLNxnqew1/Zs5kAAADBAOBkVWoTjexpBbz4PNAdfIEoy1pmeaKV
    apz2Qb1y+9Cvfk9IsC/ffiy52VB4nbePcZ/lxMLx/76SjKpi94l9RF9nKRkTij6eMr6Tuz
    oBZvv+y826TNgRMHzXJaOZw5vEzaKpR51iwrx4wUgNKyFQ0rW12nXVn6J07nClv2hBEXe8
    WQoOZSOo7OyY4kZ2WNvHsVLeaphIy0rVpRCXaDdmNBt4i1seYQDepoiH3LPVcf+Bl4ECVZ
    +42DSJcOLbEE8TOwAAACBsZW9uZWxATGVvbmVscy1NYWNCb29rLVByby5sb2NhbAE=
    -----END OPENSSH PRIVATE KEY-----