apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../../../base/charts/app-of-apps/web-trackeo-pricing/app-tracking

helmCharts:
- name: tracking-micro-services
  releaseName: tracking-micro-services-aoa
  valuesFile: ./patch-values.yaml