environment: dev

appOne:
  appName: api-chat-bot
  projectName: api-chatbot
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  destination:
    server: https://kubernetes.default.svc
  source:
    path: customer-experience/overlays/dev/app-tracking/tracking-micro-services/api-chat-bot
    repoURL: git@github.com:cortiz2024/test_image_customer.git
    targetRevision: HEAD