environment: dev

appOne:
  appName: api-traducciones
  projectName: api-traducciones
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  destination:
    server: https://kubernetes.default.svc
  source:
    path: customer-experience/overlays/dev/app-tracking/tracking-micro-services/api-traducciones
    repoURL: git@github.com:cortiz2024/test_image_customer.git
    targetRevision: HEAD