namespace: argocd
environment: dev

projects:
  projectOne:
    name: api-chatbot
    sourceRepos:
      - '!ssh://git@GITHUB.com:infrastructure-services/test'
    destinations:
      - namespace: '*'
        server: 'https://kubernetes.default.svc'
  projectTwo:
    name: api-traducciones
  projectThree:
    name: web-historia-de-envios