namespace: argocd
project:
  name:
    prefix: main-project

spec:
  sourceRepos:
    - '!ssh://git@GITHUB.com:infrastructure-services/test'
    - '!https://gitlab.com/group/**'
    - '*'
  destinations:
    - namespace: '!kube-system'
      server: '*'
    - namespace: '*'
      server: '!https://unknown-*'
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    group: '*'
    kind: '*'

applications:
  projects:
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    path: overlays/test/projects
    repoURL: git@github.com:cortiz2024/test_image.git
    targetRevision: HEAD
  apps:
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    path: overlays/test/apps-of-apps
    repoURL: git@github.com:cortiz2024/test_image.git
    targetRevision: HEAD

applicationsprod:
  projects:
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    path: overlays/production/projects
    repoURL: git@github.com:cortiz2024/test_image.git
    targetRevision: HEAD
  apps:
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    path: overlays/production/apps-of-apps
    repoURL: git@github.com:cortiz2024/test_image.git
    targetRevision: HEAD

repoSecret:
  name: main-private-repo-secret
  stringData:
    type: git
    url: git@github.com:cortiz2024/test_image.git

registrySecret:
  name: main-private-registry-secret
  stringData:
    type: helm
    url: ghcr.io/cortiz2024/demo_app
    username: cortiz2024
    password: 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