environment: dev

appOne:
  appName: api-chat-bot
  projectName: api-chatbot
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  destination:
    server: https://kubernetes.default.svc
  source:
    path: customer-experience/overlays/dev/app-tracking/tracking-micro-services/api-chat-bot
    repoURL: git@github.com:cortiz2024/test_image_customer.git
    targetRevision: HEAD
appTwo:
  appName: api-traducciones
  projectName: api-traducciones
  source:
    path: customer-experience/overlays/dev/app-tracking/tracking-micro-services/api-traducciones
appThree:
  appName: web-hist-envios
  projectName: web-historia-de-envios
  source:
    path: customer-experience/overlays/dev/app-tracking/tracking-micro-services/web-hist-envios