environment: dev

appOne:
  appName: web-hist-envios
  projectName: web-historia-de-envios
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  destination:
    server: https://kubernetes.default.svc
  source:
    path: customer-experience/overlays/dev/app-tracking/tracking-micro-services/web-hist-envios
    repoURL: git@github.com:cortiz2024/test_image_customer.git
    targetRevision: HEAD