apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# resources:
# - second-python-app.yaml

helmGlobals:
  chartHome: ../../../../../base/charts

helmCharts:
- name: python-apps
  releaseName: app
  valuesFile: ./patch-values.yaml