namespace: apps-three
environment: dev

appOne:
  appName: web-hist-envios-app
  projectName: project-web-historia-de-envios
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  destination:
    server: https://kubernetes.default.svc
  source:
    chartName: python-chart
    repoURL: ghcr.io/cortiz2024/demo_app
    targetRevision: 8.1.0-29-test